import type {Metadata} from "next";
import {Geist, Geist_Mono, Mona_Sans} from "next/font/google";
import "./globals.css"
import {Toaster} from "react-hot-toast";


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});


const monaSans = Mona_Sans({
    variable: "--font-mona-sans",
    subsets: ["latin"]
})


export const metadata: Metadata = {
    title: "Mi entrenamiento",
    description: "Generated by Yoan",
};


export default function RootLayout({children}: Readonly<{ children: React.ReactNode }>) {


    return (
        <html lang="en" className="dark">
        <body className={`${monaSans.variable}  antialiased pattern`}>
        <Toaster position="top-center" reverseOrder={false}/>
        {children}

        </body>
        </html>

    );
}
